.TH WESNOTH-LOVE 6 "June 7 2018"
.SH NAME
wesnoth-love \- Strategy Game.
.SH SYNOPSIS
.B wesnoth-love
.SH DESCRIPTION
 Wesnoth is a turn based fantasy strategy game.
.PP
\fBwesnoth-love\fP is a turn based fantasy game built using Lua/Moonscript and the LOVE framework.This command executes a bash script of the wesnoth-love package against the love executable.
.SH OPTIONS
 None.
.SH SEE ALSO
.BR love (1),
.br
.SH AUTHOR
wesnoth-love was written by Fabian Mueller and other Wesnoth developers.
